# Generated by Django 4.0 on 2021-12-20 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Project Title')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
                ('type', models.CharField(choices=[('BE', 'Back End'), ('FE', 'Front End'), ('IOS', 'Ios'), ('AID', 'Android')], max_length=5)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Project Title')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('IMPVMT', 'Improvement'), ('TASK', 'Task')], max_length=15)),
                ('priority', models.CharField(choices=[('P2', 'High'), ('P1', 'Medium'), ('P0', 'Low')], max_length=6)),
                ('status', models.CharField(choices=[('S2', 'To Do'), ('S1', 'In Progress'), ('S0', 'Terminated')], max_length=6)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignee_User_Id', to='authentication.user', verbose_name='Assignee User Id')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author_User_Id', to='authentication.user', verbose_name='Author User Id')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AUTH', 'Author'), ('CONTRI', 'Contributor')], max_length=20)),
                ('role', models.CharField(max_length=128, verbose_name='Contributor Role')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softDeskApi.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Author User Id')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softDeskApi.issue', verbose_name='Issue Id')),
            ],
        ),
    ]
