# Generated by Django 4.0 on 2021-12-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0002_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='projet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Project_Id', to='softDeskApi.project', verbose_name='Project Id'),
            preserve_default=False,
        ),
    ]
