# Generated by Django 4.0 on 2021-12-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0003_issue_projet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='projet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='softDeskApi.project', verbose_name='Project Id'),
        ),
    ]
