# Generated by Django 4.0 on 2021-12-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0004_alter_issue_projet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='projet_id',
            new_name='projet',
        ),
    ]
