# Generated by Django 4.0 on 2021-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0005_rename_projet_id_issue_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='type',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTH', 'Author'), ('CONTRI', 'Contributor')], max_length=20, verbose_name='Contributor Role'),
        ),
    ]
