# Generated by Django 4.0 on 2021-12-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0006_remove_contributor_type_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('CONTRIBUTOR', 'Contributor')], max_length=20, verbose_name='Contributor Role'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=15),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('TERMINATED', 'Terminated')], max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BACK_END', 'Back End'), ('FRONT_END', 'Front End'), ('IOS', 'Ios'), ('ANDROID', 'Android')], max_length=15),
        ),
    ]
