# Generated by Django 4.0 on 2021-12-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_alter_user_date_joined_alter_user_is_active_and_more'),
        ('softDeskApi', '0008_remove_project_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(related_name='contributions', through='softDeskApi.Contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_project', to='softDeskApi.project'),
        ),
    ]
