# Generated by Django 4.0 on 2022-01-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0009_project_contributor_alter_contributor_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='projet',
            new_name='project',
        ),
    ]
