# Generated by Django 4.0 on 2022-01-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0010_rename_projet_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMPROVEMENT', 'Improvement'), ('TASK', 'Task')], max_length=15),
        ),
    ]
