# Generated by Django 4.0 on 2022-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0011_alter_issue_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='projet',
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMPVMT', 'Improvement'), ('TASK', 'Task')], max_length=15),
        ),
    ]
