# Generated by Django 4.0 on 2022-01-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softDeskApi', '0012_rename_project_issue_projet_alter_issue_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='projet',
            new_name='project',
        ),
    ]
