# Generated by Django 4.0 on 2022-01-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_date_joined_alter_user_is_active_and_more'),
        ('softDeskApi', '0013_rename_projet_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.user', verbose_name='Author User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='softDeskApi.issue', verbose_name='Issue'),
        ),
    ]
